services:
  mongodb:
    image: mongo:latest
    container_name: coment-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27016:27017"
    volumes:
      - ./mongodb_data:/data/db

      